name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  run-tests:
    runs-on: ubuntu-latest
    steps:
    - name: my-artifact
      uses: actions/upload-artifact@v3
      with:
        path: pom.xml

    - name: test
      run: |
        curl https://api.github.com/repos/konor8812/demoproject1/actions/artifacts

#      - name: Git clone repo
#        uses: actions/checkout@v3
#
#      - name: Set up JDK 11
#        uses: actions/setup-java@v3
#        with:
#          java-version: '11'
#          distribution: 'temurin'
#          cache: maven
#
#      - name: Run  tests
#        run: |
#          cd demo-client
#          mvn package
#
#      - name: Get code coverage report
#        run: |
#          mvn jacoco:report
#
#      - name: Add Coverage PR Comment
#        uses: madrapps/jacoco-report@v1.3
#        with:
#          paths: ${{ github.workspace }}/demo-client/target/site/jacoco/jacoco.xml
#          token: ${{ secrets.GITHUB_TOKEN }}
#          min-coverage-overall: 40



#  ci-build-push-artifact-to-dockerhub:
#    needs: run-tests
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Git clone repo
#        uses: actions/checkout@v3
#
#      - name: Build with Maven
#        run: mvn package -Dmaven.test.skip
#
#      - name: Login to DockerHub
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#
#      - name: Build demo-server Docker image
#        run: docker build -t konor881/imdb-analyzer-server:latest demo-server/
#
#      - name: Build demo-client Docker image
#        run: docker build -t konor881/imdb-analyzer-client:latest demo-client/
#
#      - name: Push demo-server Docker image to Dockerhub
#        run: docker push konor881/imdb-analyzer-server:latest
#
#      - name: Push demo-client Docker image to Dockerhub
#        run: docker push konor881/imdb-analyzer-client:latest
